services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "the_Real@riginal01"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - ./SchemaAndData.sql:/tmp/SchemaAndData.sql
      - sql_data:/var/opt/mssql
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  redis:
    image: redis:latest
    container_name: my-redis-instance
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  sql_data:
  mongo_data:
  redis_data: