services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "the_Real@riginal01"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - ./SchemaAndData.sql:/tmp/SchemaAndData.sql
      - sql_data:/var/opt/mssql
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  sql_data:
  mongo_data: